
export const GET_CONNECTED = "GET_CONNECTED"
export const GET_CONNECTED_ERROR = "GET_CONNECTED_ERROR"
export const GET_CONNECTED_SUCCESS = "GET_CONNECTED_SUCCESS"

export const GET_DISCONNECTED = "GET_DISCONNECTED"
export const GET_DISCONNECTED_ERROR = "GET_DISCONNECTED_ERROR"
export const GET_DISCONNECTED_SUCCESS = "GET_CONNECTED_SUCCESS"


export const GET_ACCOUNT = "GET_ACCOUNT"
export const GET_ACCOUNT_ERROR = "GET_ACCOUNT_ERROR"
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS"

export const CREATE_ACCOUNT = "CREATE_ACCOUNT"
export const CREATE_ACCOUNT_ERROR = "CREATE_ACCOUNT_ERROR"
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS"

export const EDIT_ACCOUNT = "EDIT_ACCOUNT"
export const EDIT_ACCOUNT_ERROR = "EDIT_ACCOUNT_ERROR"
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCCOUNT_SUCCESS"

export const DELETE_ACCOUNT = "DELETE_ACCOUNT"
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR"
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS"

export const ACCEPT_COOKIE = "ACCEPT_COOKIE"