
export const GET_BIDS_OF_OBJECT = "GET_BIDS_OF_OBJECT"
export const GET_BIDS_OF_OBJECT_ERROR = "GET_BIDS_OF_OBJECT_ERROR"
export const GET_BIDS_OF_OBJECT_SUCCESS = "GET_BIDS_OF_OBJECT_SUCCESS"

export const CREATE_BID = "CREATE_BID"
export const CREATE_BID_ERROR = "CREATE_BID_ERROR"
export const CREATE_BID_SUCCESS = "CREATE_BID_SUCCESS"