export const GET_DETAILLED_OBJECT = "GET_DETAILLED_OBJECT"
export const GET_DETAILLED_OBJECT_ERROR = "GET_DETAILLED_OBJECT_ERROR"
export const GET_DETAILLED_OBJECT_SUCCESS = "GET_DETAILLED_OBJECT_SUCCESS"
