
export const GET_IMAGES_OF_OBJECT = "GET_IMAGES_OF_OBJECT"
export const GET_IMAGES_OF_OBJECT_ERROR = "GET_IMAGES_OF_OBJECT_ERROR"
export const GET_IMAGES_OF_OBJECT_SUCCESS = "GET_IMAGES_OF_OBJECT_SUCCESS"

export const EDIT_IMAGE_OF_OBJECT = "EDIT_IMAGE_OF_OBJECT"
export const EDIT_IMAGE_OF_OBJECT_ERROR = "EDIT_IMAGE_OF_OBJECT_ERROR"
export const EDIT_IMAGE_OF_OBJECT_SUCCESS = "EDIT_IMAGE_OF_OBJECT_SUCCESS"

export const DELETE_IMAGE_OF_OBJECT = "DELETE_IMAGE_OF_OBJECT"
export const DELETE_IMAGE_OF_OBJECT_ERROR = "DELETE_IMAGE_OF_OBJECT_ERROR"
export const DELETE_IMAGE_OF_OBJECT_SUCCESS = "DELETE_IMAGE_OF_OBJECT_SUCCESS"

export const CREATE_IMAGE_OF_OBJECT = "CREATE_IMAGE_OF_OBJECT"
export const CREATE_IMAGE_OF_OBJECT_ERROR = "CREATE_IMAGE_OF_OBJECT_ERROR"
export const CREATE_IMAGE_OF_OBJECT_SUCCESS = "CREATE_IMAGE_OF_OBJECT_SUCCESS"
