
export const GET_OBJECTS = "GET_OBJECTS"
export const GET_OBJECTS_ERROR = "GET_OBJECTS_ERROR"
export const GET_OBJECTS_SUCCESS = "GET_OBJECTS_SUCCESS"

export const EDIT_OBJECT = "EDIT_OBJECT"
export const EDIT_OBJECT_ERROR = "EDIT_OBJECT_ERROR"
export const EDIT_OBJECT_SUCCESS = "EDIT_OBJECT_SUCCESS"

export const CREATE_OBJECT = "CREATE_OBJECT"
export const CREATE_OBJECT_ERROR = "CREATE_OBJECT_ERROR"
export const CREATE_OBJECT_SUCCESS = "CREATE_OBJECT_SUCCESS"

export const DELETE_OBJECT = "DELETE_OBJECT"
export const DELETE_OBJECT_ERROR = "DELETE_OBJECT_ERROR"
export const DELETE_OBJECT_SUCCESS = "DELETE_OBJECT_SUCCESS"

export const GET_NEXT_OBJECTS_PAGE = "GET_NEXT_OBJECTS_PAGE"
export const GET_NEXT_OBJECTS_PAGE_ERROR = "GET_NEXT_OBJECTS_PAGE_ERROR"
export const GET_NEXT_OBJECTS_PAGE_SUCCESS = "GET_NEXT_OBJECTS_PAGE_SUCCESS"