
export const GET_OBJECT = "GET_OBJECT"
export const GET_OBJECT_ERROR = "GET_OBJECT_ERROR"
export const GET_OBJECT_SUCCESS = "GET_OBJECT_SUCCESS"

export const GET_OBJECTS = "GET_OBJECTS"
export const GET_OBJECTS_ERROR = "GET_OBJECTS_ERROR"
export const GET_OBJECTS_SUCCESS = "GET_OBJECTS_SUCCESS"

export const EDIT_OBJECT = "EDIT_OBJECT"
export const EDIT_OBJECT_ERROR = "EDIT_OBJECT_ERROR"
export const EDIT_OBJECT_SUCCESS = "EDIT_OBJECT_SUCCESS"

export const CREATE_OBJECT = "CREATE_OBJECT"
export const CREATE_OBJECT_ERROR = "CREATE_OBJECT_ERROR"
export const CREATE_OBJECT_SUCCESS = "CREATE_OBJECT_SUCCESS"

export const DELETE_OBJECT = "DELETE_OBJECT"
export const DELETE_OBJECT_ERROR = "DELETE_OBJECT_ERROR"
export const DELETE_OBJECT_SUCCESS = "DELETE_OBJECT_SUCCESS"

export const GET_NEXT_OBJECTS_PAGE = "GET_NEXT_OBJECTS_PAGE"
export const GET_NEXT_OBJECTS_PAGE_ERROR = "GET_NEXT_OBJECTS_PAGE_ERROR"
export const GET_NEXT_OBJECTS_PAGE_SUCCESS = "GET_NEXT_OBJECTS_PAGE_SUCCESS"

export const GET_BIDDED_OBJECTS = "GET_BIDDED_OBECTS"
export const GET_BIDDED_OBJECTS_ERROR = "GET_BIDDED_OBECTS_ERROR"
export const GET_BIDDED_OBJECTS_SUCCES = "GET_BIDDED_OBECTS_SUCCES"

export const GET_SELLED_OBJECTS = "GET_SELLED_OBECTS"
export const GET_SELLED_OBJECTS_ERROR = "GET_SELLED_OBJECTS_ERROR"
export const GET_SELLED_OBJECTS_SUCCES = "GET_SELLED_OBJECTS_SUCCESS"

export const GET_PURCHASED_OBJECTS = "GET_PURCHASED_OBECTS"
export const GET_PURCHASED_OBJECTS_ERROR = "GET_PURCHASED_OBECTS_ERROR"
export const GET_PURCHASED_OBJECTS_SUCCES = "GET_PURCHASED_OBECTS_SUCCES"

export const GET_ACTIVE_OBJECTS = "GET_ACTIVE_OBECTS"
export const GET_ACTIVE_OBJECTS_ERROR = "GET_ACTIVE_OBECTS_ERROR"
export const GET_ACTIVE_OBJECTS_SUCCES = "GET_ACTIVE_OBECTS_SUCCES"

export const GET_ENDED_OBJECTS = "GET_ENDED_OBECTS"
export const GET_ENDED_OBJECTS_ERROR = "GET_ENDED_OBECTS_ERROR"
export const GET_ENDED_OBJECTS_SUCCES = "GET_ENDED_OBECTS_SUCCES"

export const GET_FOLLOWED_OBJECTS = "GET_FOLLOWED_OBECTS"
export const GET_FOLLOWED_OBJECTS_ERROR = "GET_FOLLOWED_OBECTS_ERROR"
export const GET_FOLLOWED_OBJECTS_SUCCES = "GET_FOLLOWED_OBECTS_SUCCES"