export const GET_OPERATIONS = "GET_OPERATIONS"
export const GET_OPERATIONS_ERROR = "GET_OPERATIONS_ERROR"
export const GET_OPERATIONS_SUCCESS = "GET_OPERATIONS_SUCCESS"

export const CREATE_OPERATION = "CREATE_OPERATION"
export const CREATE_OPERATION_ERROR = "CREATE_OPERATION_ERROR"
export const CREATE_OPERATION_SUCCESS = "CREATE_OPERATION_SUCCESS"