
export const GET_QUESTIONS_OF_OBJECT = "GET_QUESTIONS_OF_OBJECT"
export const GET_QUESTIONS_OF_OBJECT_ERROR = "GET_QUESTIONS_OF_OBJECT_ERROR"
export const GET_QUESTIONS_OF_OBJECT_SUCCESS = "GET_QUESTIONS_OF_OBJECT_SUCCESS"


export const GET_NEXT_QUESTIONS_OF_OBJECT_PAGE = "GET_NEXT_QUESTIONS_OF_OBJECT_PAGE"
export const GET_NEXT_QUESTIONS_OF_OBJECT_PAGE_ERROR = "GET_NEXT_QUESTIONS_OF_OBJECT_PAGE_ERROR"
export const GET_NEXT_QUESTIONS_OF_OBJECT_PAGE_SUCCESS = "GET_NEXT_QUESTIONS_OF_OBJECT_PAGE_SUCCESS"

export const DELETE_QUESTION_OF_OBJECT = "DELETE_QUESTION_OF_OBJECT"
export const DELETE_QUESTION_OF_OBJECT_ERROR ="DELETE_QUESTION_OF_OBJECT_ERROR"
export const DELETE_QUESTION_OF_OBJECT_SUCCESS = "DELETE_QUESTION_OF_OBJECT_SUCCESS"


export const GET_QUESTIONS_OF_USER = "GET_QUESTIONS_OF_USER"
export const GET_QUESTIONS_OF_USER_ERROR = "GET_QUESTIONS_OF_USER_ERROR"
export const GET_QUESTIONS_OF_USER_SUCCESS = "GET_QUESTIONS_OF_USER_SUCCESS"

export const CREATE_QUESTIONS_OF_OBJECT = "CREATE_QUESTION_OF_OBJECT"
export const CREATE_QUESTIONS_OF_OBJECT_SUCCESS = "CREATE_QUESTION_OF_OBJECT_SUCCESS"
export const CREATE_QUESTIONS_OF_OBJECT_ERROR = "CREATE_QUESTION_OF_OBJECT_ERROR"