
export const GET_QUESTIONS_OF_OBJECT = "GET_QUESTIONS_OF_OBJECT"
export const GET_QUESTIONS_OF_OBJECT_ERROR = "GET_QUESTIONS_OF_OBJECT_ERROR"
export const GET_QUESTIONS_OF_OBJECT_SUCCESS = "GET_QUESTIONS_OF_OBJECT_SUCCESS"

export const DELETE_QUESTION_OF_OBJECT = "DELETE_QUESTION_OF_OBJECT"
export const DELETE_QUESTION_OF_OBJECT_ERROR ="DELETE_QUESTION_OF_OBJECT_ERROR"
export const DELETE_QUESTION_OF_OBJECT_SUCCESS = "DELETE_QUESTION_OF_OBJECT_SUCCESS"


export const GET_QUESTIONS_OF_USER = "GET_QUESTIONS_OF_USER"
export const GET_QUESTIONS_OF_USER_ERROR = "GET_QUESTIONS_OF_USER_ERROR"
export const GET_QUESTIONS_OF_USER_SUCCESS = "GET_QUESTIONS_OF_USER_SUCCESS"