
export const GET_QUESTIONS_OF_USER = "GET_QUESTIONS_OF_USER"
export const GET_QUESTIONS_OF_USER_ERROR = "GET_QUESTIONS_OF_USER_ERROR"
export const GET_QUESTIONS_OF_USER_SUCCESS = "GET_QUESTIONS_OF_USER_SUCCESS"