
export const GET_USER = "GET_USER"
export const GET_USER_ERROR = "GET_USER_ERROR"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"

export const GET_DETAILLED_USER = "GET_DETAILLED_USER"
export const GET_DETAILLED_USER_ERROR = "GET_DETAILLED_USER_ERROR"
export const GET_DETAILLED_USER_SUCCESS = "GET_DETAILLED_USER_SUCCESS"

export const EDIT_USER = "EDIT_USER"
export const EDIT_USER_ERROR = "EDIT_USER_ERROR"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"

