import { Component } from "react";

class HelpPage extends Component {

    render() {
        return(
            <div>
                <div className="ebazar-contact">
                    <h3>Vous avez des questions ?</h3>
                    <button>Contacter EBAZAR</button>
                </div>
                <h3>Commencer à vendre</h3>
                <p>

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut lectus lacinia, eleifend mi id, luctus tortor. Nulla facilisi. Suspendisse viverra sem eu imperdiet euismod. Fusce vel turpis a nibh bibendum finibus. Sed dapibus lacus eget est rhoncus, vel lacinia nibh suscipit. Sed ut condimentum arcu. Donec faucibus lacus in nisi maximus, et imperdiet mi lobortis. Aenean ultrices vel lacus suscipit aliquam. Morbi cursus ante felis, vitae sollicitudin diam efficitur ut. Donec magna leo, ultrices et semper malesuada, porttitor sit amet nibh. Nullam dictum, dolor malesuada posuere interdum, ante nibh dapibus metus, vel hendrerit turpis felis ut ipsum. Praesent enim tortor, hendrerit sit amet elit eget, commodo hendrerit ligula. Cras a libero lacinia, blandit mi vitae, semper purus. Quisque a felis posuere, placerat elit nec, feugiat urna. Aenean malesuada lorem venenatis augue pretium, at fringilla libero semper. Vivamus et rutrum nibh.

                    Fusce mollis justo tristique tellus facilisis, euismod blandit est ultricies. Donec ullamcorper leo velit, at placerat mauris aliquam eu. Nullam iaculis mi a quam efficitur laoreet. Nullam at orci elementum, blandit est non, aliquet turpis. Donec urna ligula, cursus vel suscipit id, sollicitudin et nulla. Morbi est mi, ultricies in condimentum quis, interdum ac erat. Mauris et malesuada orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eu ligula rutrum, hendrerit tortor vitae, accumsan lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum felis ligula, feugiat lobortis mattis at, egestas in est. Etiam faucibus velit sed nulla porttitor suscipit. Curabitur eu pellentesque erat, sed sollicitudin ipsum. Curabitur tristique ultricies sem vitae sollicitudin. Cras eget ultricies mi. Donec facilisis sapien bibendum viverra consequat.

                    Curabitur scelerisque vulputate scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ac varius velit. Cras erat risus, feugiat vitae facilisis quis, rhoncus ut odio. Cras cursus sed metus et tempor. Nunc erat eros, imperdiet ut nibh sed, convallis pretium mauris. Curabitur elementum at velit in luctus. Sed vehicula sed odio sit amet lobortis. Sed eu molestie justo. Ut turpis ipsum, rutrum vel tempor sed, faucibus vitae metus. Nunc neque turpis, efficitur eu ante quis, cursus consectetur neque. Donec augue mauris, bibendum eget mollis vel, interdum at quam. Nam eget dignissim justo, ac rutrum ex. Quisque eget maximus sem, sed suscipit arcu. Maecenas ac ligula ut tortor euismod tempus sit amet et sapien.

                    Integer ex orci, viverra quis ex in, congue feugiat velit. Ut varius rutrum est mollis consequat. Aenean feugiat tempus fringilla. Curabitur sed pretium diam. Suspendisse sed tellus nisl. Pellentesque sollicitudin varius erat id porta. Integer euismod efficitur eros at elementum. Fusce eget pharetra neque. Donec congue feugiat tellus, nec maximus felis blandit at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque a pretium metus. Pellentesque iaculis metus vel ipsum vulputate scelerisque.

                    Nulla vitae pellentesque lacus. Vestibulum pharetra efficitur nunc at ultricies. Donec eget sapien dui. Nulla consectetur, velit ut malesuada tempor, odio urna faucibus odio, et imperdiet risus risus eu lacus. Sed vitae nisi vel risus mollis blandit. Etiam et molestie ante, porta pharetra ligula. Pellentesque semper nisi magna, consequat faucibus quam tempus ut. 
                </p>
                <h3>Facturation</h3>
                <p>

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut lectus lacinia, eleifend mi id, luctus tortor. Nulla facilisi. Suspendisse viverra sem eu imperdiet euismod. Fusce vel turpis a nibh bibendum finibus. Sed dapibus lacus eget est rhoncus, vel lacinia nibh suscipit. Sed ut condimentum arcu. Donec faucibus lacus in nisi maximus, et imperdiet mi lobortis. Aenean ultrices vel lacus suscipit aliquam. Morbi cursus ante felis, vitae sollicitudin diam efficitur ut. Donec magna leo, ultrices et semper malesuada, porttitor sit amet nibh. Nullam dictum, dolor malesuada posuere interdum, ante nibh dapibus metus, vel hendrerit turpis felis ut ipsum. Praesent enim tortor, hendrerit sit amet elit eget, commodo hendrerit ligula. Cras a libero lacinia, blandit mi vitae, semper purus. Quisque a felis posuere, placerat elit nec, feugiat urna. Aenean malesuada lorem venenatis augue pretium, at fringilla libero semper. Vivamus et rutrum nibh.

                    Fusce mollis justo tristique tellus facilisis, euismod blandit est ultricies. Donec ullamcorper leo velit, at placerat mauris aliquam eu. Nullam iaculis mi a quam efficitur laoreet. Nullam at orci elementum, blandit est non, aliquet turpis. Donec urna ligula, cursus vel suscipit id, sollicitudin et nulla. Morbi est mi, ultricies in condimentum quis, interdum ac erat. Mauris et malesuada orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eu ligula rutrum, hendrerit tortor vitae, accumsan lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum felis ligula, feugiat lobortis mattis at, egestas in est. Etiam faucibus velit sed nulla porttitor suscipit. Curabitur eu pellentesque erat, sed sollicitudin ipsum. Curabitur tristique ultricies sem vitae sollicitudin. Cras eget ultricies mi. Donec facilisis sapien bibendum viverra consequat.

                    Curabitur scelerisque vulputate scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ac varius velit. Cras erat risus, feugiat vitae facilisis quis, rhoncus ut odio. Cras cursus sed metus et tempor. Nunc erat eros, imperdiet ut nibh sed, convallis pretium mauris. Curabitur elementum at velit in luctus. Sed vehicula sed odio sit amet lobortis. Sed eu molestie justo. Ut turpis ipsum, rutrum vel tempor sed, faucibus vitae metus. Nunc neque turpis, efficitur eu ante quis, cursus consectetur neque. Donec augue mauris, bibendum eget mollis vel, interdum at quam. Nam eget dignissim justo, ac rutrum ex. Quisque eget maximus sem, sed suscipit arcu. Maecenas ac ligula ut tortor euismod tempus sit amet et sapien.

                    Integer ex orci, viverra quis ex in, congue feugiat velit. Ut varius rutrum est mollis consequat. Aenean feugiat tempus fringilla. Curabitur sed pretium diam. Suspendisse sed tellus nisl. Pellentesque sollicitudin varius erat id porta. Integer euismod efficitur eros at elementum. Fusce eget pharetra neque. Donec congue feugiat tellus, nec maximus felis blandit at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque a pretium metus. Pellentesque iaculis metus vel ipsum vulputate scelerisque.

                    Nulla vitae pellentesque lacus. Vestibulum pharetra efficitur nunc at ultricies. Donec eget sapien dui. Nulla consectetur, velit ut malesuada tempor, odio urna faucibus odio, et imperdiet risus risus eu lacus. Sed vitae nisi vel risus mollis blandit. Etiam et molestie ante, porta pharetra ligula. Pellentesque semper nisi magna, consequat faucibus quam tempus ut. 
                </p>
                <h3>Livraison</h3>
                <p>

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut lectus lacinia, eleifend mi id, luctus tortor. Nulla facilisi. Suspendisse viverra sem eu imperdiet euismod. Fusce vel turpis a nibh bibendum finibus. Sed dapibus lacus eget est rhoncus, vel lacinia nibh suscipit. Sed ut condimentum arcu. Donec faucibus lacus in nisi maximus, et imperdiet mi lobortis. Aenean ultrices vel lacus suscipit aliquam. Morbi cursus ante felis, vitae sollicitudin diam efficitur ut. Donec magna leo, ultrices et semper malesuada, porttitor sit amet nibh. Nullam dictum, dolor malesuada posuere interdum, ante nibh dapibus metus, vel hendrerit turpis felis ut ipsum. Praesent enim tortor, hendrerit sit amet elit eget, commodo hendrerit ligula. Cras a libero lacinia, blandit mi vitae, semper purus. Quisque a felis posuere, placerat elit nec, feugiat urna. Aenean malesuada lorem venenatis augue pretium, at fringilla libero semper. Vivamus et rutrum nibh.

                    Fusce mollis justo tristique tellus facilisis, euismod blandit est ultricies. Donec ullamcorper leo velit, at placerat mauris aliquam eu. Nullam iaculis mi a quam efficitur laoreet. Nullam at orci elementum, blandit est non, aliquet turpis. Donec urna ligula, cursus vel suscipit id, sollicitudin et nulla. Morbi est mi, ultricies in condimentum quis, interdum ac erat. Mauris et malesuada orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla eu ligula rutrum, hendrerit tortor vitae, accumsan lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum felis ligula, feugiat lobortis mattis at, egestas in est. Etiam faucibus velit sed nulla porttitor suscipit. Curabitur eu pellentesque erat, sed sollicitudin ipsum. Curabitur tristique ultricies sem vitae sollicitudin. Cras eget ultricies mi. Donec facilisis sapien bibendum viverra consequat.

                    Curabitur scelerisque vulputate scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ac varius velit. Cras erat risus, feugiat vitae facilisis quis, rhoncus ut odio. Cras cursus sed metus et tempor. Nunc erat eros, imperdiet ut nibh sed, convallis pretium mauris. Curabitur elementum at velit in luctus. Sed vehicula sed odio sit amet lobortis. Sed eu molestie justo. Ut turpis ipsum, rutrum vel tempor sed, faucibus vitae metus. Nunc neque turpis, efficitur eu ante quis, cursus consectetur neque. Donec augue mauris, bibendum eget mollis vel, interdum at quam. Nam eget dignissim justo, ac rutrum ex. Quisque eget maximus sem, sed suscipit arcu. Maecenas ac ligula ut tortor euismod tempus sit amet et sapien.

                    Integer ex orci, viverra quis ex in, congue feugiat velit. Ut varius rutrum est mollis consequat. Aenean feugiat tempus fringilla. Curabitur sed pretium diam. Suspendisse sed tellus nisl. Pellentesque sollicitudin varius erat id porta. Integer euismod efficitur eros at elementum. Fusce eget pharetra neque. Donec congue feugiat tellus, nec maximus felis blandit at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque a pretium metus. Pellentesque iaculis metus vel ipsum vulputate scelerisque.

                    Nulla vitae pellentesque lacus. Vestibulum pharetra efficitur nunc at ultricies. Donec eget sapien dui. Nulla consectetur, velit ut malesuada tempor, odio urna faucibus odio, et imperdiet risus risus eu lacus. Sed vitae nisi vel risus mollis blandit. Etiam et molestie ante, porta pharetra ligula. Pellentesque semper nisi magna, consequat faucibus quam tempus ut. 
                </p>
            </div>
        )
    }
}

export default HelpPage