# Generated by Django 3.1.7 on 2021-08-15 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebay_objects', '0003_delete_purchasedobject'),
        ('ebay_account', '0002_auto_20210811_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCancelled', models.BooleanField(blank=True, default=0, null=True)),
                ('isComplete', models.BooleanField(blank=True, default=0, null=True)),
                ('isShipped', models.BooleanField(blank=True, default=0, null=True)),
                ('shippingNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('shippingCompany', models.CharField(blank=True, max_length=120, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=0, null=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_objects.object')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay_account.operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
