# Generated by Django 3.1.5 on 2021-06-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210607_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='street_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
