# Generated by Django 3.1.5 on 2021-06-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210607_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
