# Generated by Django 3.1.7 on 2021-08-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOfObject', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('actualPrice', models.FloatField(default=0)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('durationInDays', models.IntegerField(default=7)),
                ('endingDate', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isSelled', models.BooleanField(default=False)),
                ('reservePrice', models.FloatField(default=0)),
                ('shippingPrice', models.FloatField()),
                ('returnPolicy', models.BooleanField()),
                ('mainImage', models.ImageField(upload_to='')),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateOfObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCancelled', models.BooleanField(blank=True, default=0, null=True)),
                ('isComplete', models.BooleanField(blank=True, default=0, null=True)),
                ('isShipped', models.BooleanField(blank=True, default=0, null=True)),
                ('shippingNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('shippingCompany', models.CharField(blank=True, max_length=120, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=0, null=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_objects.object')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay_account.operation')),
            ],
        ),
    ]
