# Generated by Django 3.1.7 on 2021-08-11 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebay_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedobject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_base.category'),
        ),
        migrations.AddField(
            model_name='object',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_objects.stateofobject'),
        ),
        migrations.AddField(
            model_name='object',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_base.subcategory'),
        ),
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_objects.object'),
        ),
        migrations.AddField(
            model_name='followedobject',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_objects.object'),
        ),
        migrations.AddField(
            model_name='followedobject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
