# Generated by Django 3.1.7 on 2021-06-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedobject',
            name='shippingCompany',
        ),
        migrations.RemoveField(
            model_name='purchasedobject',
            name='shippingNumber',
        ),
    ]
