# Generated by Django 3.1.7 on 2021-06-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0005_auto_20210626_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='isComplete',
        ),
        migrations.AddField(
            model_name='operation',
            name='shippingCompany',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
