# Generated by Django 3.1.7 on 2021-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0006_auto_20210626_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='shippingCompany',
        ),
        migrations.AddField(
            model_name='purchasedobject',
            name='shippingCompany',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
