# Generated by Django 3.1.7 on 2021-06-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0007_auto_20210626_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtype',
            name='name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
