# Generated by Django 3.1.7 on 2021-06-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0008_auto_20210626_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
