# Generated by Django 3.1.7 on 2021-06-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0009_purchasemethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedobject',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebay_api.purchasemethod'),
        ),
    ]
