# Generated by Django 3.1.7 on 2021-06-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0010_purchasedobject_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedobject',
            name='method',
        ),
        migrations.AddField(
            model_name='purchasedobject',
            name='paymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay_api.purchasemethod'),
        ),
    ]
