# Generated by Django 3.1.7 on 2021-06-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0011_auto_20210626_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedobject',
            old_name='paymentMethod',
            new_name='purchaseMethod',
        ),
    ]
