# Generated by Django 3.1.7 on 2021-06-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0012_auto_20210626_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='purchased',
        ),
        migrations.RemoveField(
            model_name='purchasedobject',
            name='purchaseMethod',
        ),
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(default='2021-06-07'),
        ),
        migrations.AddField(
            model_name='purchasedobject',
            name='date',
            field=models.DateField(default='2021-06-07'),
        ),
        migrations.AddField(
            model_name='purchasedobject',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay_api.operation'),
        ),
    ]
