# Generated by Django 3.1.7 on 2021-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0013_auto_20210626_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchasedobject',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
