# Generated by Django 3.1.7 on 2021-06-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0014_auto_20210626_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedobject',
            name='date',
        ),
    ]
