# Generated by Django 3.1.7 on 2021-06-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0015_remove_purchasedobject_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkToOffer', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
