# Generated by Django 3.1.7 on 2021-06-30 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0017_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPerObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_api.object')),
            ],
        ),
    ]
