# Generated by Django 3.1.7 on 2021-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0018_viewperobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='isWithdrawal',
            field=models.BooleanField(default=0),
        ),
    ]
