# Generated by Django 3.1.7 on 2021-07-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0019_operation_iswithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedobject',
            name='isCancelled',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedobject',
            name='isComplete',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
