# Generated by Django 3.1.7 on 2021-07-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0020_auto_20210706_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedobject',
            name='isShipped',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
