# Generated by Django 3.1.7 on 2021-07-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0022_auto_20210706_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='ViewPerObject',
        ),
    ]
