# Generated by Django 3.1.7 on 2021-07-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0024_auto_20210707_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
