# Generated by Django 3.1.7 on 2021-07-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_api', '0025_auto_20210707_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
