# Generated by Django 3.1.7 on 2021-08-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_objects', '0001_initial'),
        ('ebay_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_objects.object'),
        ),
    ]
